### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by hollowheap**

### CODE REVIEW

**Comment by adr278** [comment]
I know this is not exacly the place to put any issue, but I'm having some problems with More Culling and Cull Less Leaves. So, instead of looking like this:



It looks like this:


(the first two are with just Cull Less Leaves enabled and no More Culling in the mods folder, I don't really like how it looks like that since it's just 1 face culling, but it's better to see the diff right there)Both mods seem to work great and all, but More Culling is overiding Cull Less Leaves, and I wanna be able to use Cull Less Leaves way of culling leaves instead of More Culling. I know it looks great and all but it doesn't really seem to cull the insides(?lol). And I really enjoy seeing that on Cull Less Leaves it looks just the way I want, and changing More culling leaves options don't really seem to do much(?), so yeah.

**Comment by CommandGenius** [comment]
> I know this is not exacly the place to put any issue, but I'm having some problems with More Culling and Cull Less Leaves. So, instead of looking like this:  
> 
> It looks like this:   (the first two are with just Cull Less Leaves enabled and no More Culling in the mods folder, I don't really like how it looks like that since it's just 1 face culling, but it's better to see the diff right there)Both mods seem to work great and all, but More Culling is overiding Cull Less Leaves, and I wanna be able to use Cull Less Leaves way of culling leaves instead of More Culling. I know it looks great and all but it doesn't really seem to cull the insides(?lol). And I really enjoy seeing that on Cull Less Leaves it looks just the way I want, and changing More culling leaves options don't really seem to do much(?), so yeah.

is this happening in 1.20.6 as well?

**Comment by adr278** [comment]
> > I know this is not exacly the place to put any issue, but I'm having some problems with More Culling and Cull Less Leaves. So, instead of looking like this:  
> > It looks like this:   (the first two are with just Cull Less Leaves enabled and no More Culling in the mods folder, I don't really like how it looks like that since it's just 1 face culling, but it's better to see the diff right there)Both mods seem to work great and all, but More Culling is overiding Cull Less Leaves, and I wanna be able to use Cull Less Leaves way of culling leaves instead of More Culling. I know it looks great and all but it doesn't really seem to cull the insides(?lol). And I really enjoy seeing that on Cull Less Leaves it looks just the way I want, and changing More culling leaves options don't really seem to do much(?), so yeah.
> 
> is this happening in 1.20.6 as well?

idk, I'm on 1.21

**Comment by CommandGenius** [comment]
@adr278 try it on 1.20.6, if the issue persists on 1.20.6, then report it as an issue on the main repository.

**Comment by adr278** [comment]
> @adr278 try it on 1.20.6, if the issue persists on 1.20.6, then report it as an issue on the main repository.

alright

**Pull request merged**
